### ISSUE TITLE
action does not work on Windows

### ISSUE THREAD

**Issue by jlouros** [zwaldowski/semver-release-action#13]
```yaml
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Determine change type
      id: bump
      uses: zwaldowski/match-label-action@v2
      with:
        allowed: major,minor,patch

    - name: Set version
      id: next_version
      uses: zwaldowski/semver-release-action@v2
      with:
        dry_run: true
        bump: ${{ steps.bump.outputs.match }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
```

```
Error: Unable to locate executable file: /usr/bin/git. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.
```
