### ISSUE TITLE
Events used to trigger this action

### ISSUE THREAD

**Issue by vtertre** [zwaldowski/semver-release-action#17]
Hi
I have a hard time guessing the events I should use to trigger such an action in a release process.
The "simple" example is : 

> Create a version, f.ex., when merging to master.
>```yaml
>- id: bump
>   uses: zwaldowski/match-label-action@v1
>   with:
>     allowed: major,minor,patch
> - uses: zwaldowski/semver-release-action@v1
>   with:
>     bump: ${{ steps.bump.outputs.match }}
>     github_token: ${{ secrets.GITHUB_TOKEN }}
> ```

What trigger shall we use for "when merging to master"?
Or do you mean to run the action before merging? For example when opening a PR on master? But then the bump commit and the tag are added before the PR is merged?

**Comment by zwaldowski** [comment]
It depends on your release workflow. For instance, one of my teams uses: 

```
on:
  pull_request:
    branches:
    - main
    types:
    - closed
```

… and turns on branch protection to `main`.

You can also use:

```
on:
  push:
    branches:
      - main
```
