### ISSUE TITLE
Using example from README still not working.

### ISSUE THREAD

**Issue by mcpierce** [zwaldowski/semver-release-action#2]
(opening this since you closed the other ticket before we got to a solution)

**Overview/Goal**
For our project, we would like each checking on the develop branch to automatically increment the prerelease version and tag the commit with that updated version. We're currently wanting to use "X.Y.Z.n" to be the major, minor, patch and prerelease version elements (though we will change that scheme to suit whatever tool does the increments for us).

**Attempted Solutions**
I took the example from the README file and applied it to my project's workflow (see example YML below).

**Outcome**
When I pushed the updated workflow file I continued to get the following error message (even after following the developer's suggestion for changing the workflow):
<img width="515" alt="Screen Shot 2019-11-25 at 12 26 58 PM" src="https://user-images.githubusercontent.com/61601/69563410-0c4f2c80-0f7f-11ea-8981-88fd17056152.png">

**Desired Response**
I'm asking for the developer on this Github Action to provide a cogent example for doing the above, and to add it to a recipe for using his action that other project's can use as a guide.

**tag-develop-commits.yml**
```
name: Incremental development release tagging

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - id: bump
        name: Determine version increment
        uses: zwaldowski/match-label-action@v1
        with:
          bump: prerelease
          allowed: major,minor,patch,prerelease
      - name: Release version
        uses: zwaldowski/semver-release-action@v1
        with:
          bump: ${{ steps.bump.outputs.match }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
```
