### ISSUE TITLE
Auto Generate release notes

### ISSUE THREAD

**Issue by Pwd9000-ML** [zwaldowski/semver-release-action#21]
Would be nice to have an input that can be set to 'true' or 'false' to enable auto-generate release notes.

e.g.

```yml
inputs:
  generateReleaseNotes:
    description: 'Indicates if release notes should be automatically generated.'
    required: false
    default: 'false'
```
