### ISSUE TITLE
Is it possible to get labels from a PR in a push to branch workflow?

### ISSUE THREAD

**Issue by erikhaq** [zwaldowski/semver-release-action#35]
If I have a workflow triggered like so:

```yaml
on:
  push:
    branches: [ master ]
...
```
Is it then possible to read labels from the PR that pushed the change?
I have not been able to make it work, only with workflows triggered in the pull request context, like this:

```yaml
on:
  pull_request:
    types:
      - closed
...
    if: github.event.pull_request.merged == true
...
```
