### ISSUE TITLE
Question: Version tag with prefix

### ISSUE THREAD

**Issue by Bargamut** [zwaldowski/semver-release-action#7]
Hi there!

How I can add prefix to tag version?
I have `v0.1.0` tag in my repository and try configure action step like this:

```yaml
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - id: bump
        uses: zwaldowski/match-label-action@v2
        with:
          allowed: major,minor,patch
      - uses: zwaldowski/semver-release-action@v1
        with:
          bump: ${{ steps.bump.outputs.match }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prefix: "v"
```
and set label `minor` for pull request.

But it still `0.2.0` instead of `v0.2.0`.

Can you help me with that?

**Comment by zwaldowski** [comment]
Prefix is used [here](https://github.com/zwaldowski/semver-release-action/blob/aeb342d876448977d4e592803713d007c0032b58/index.js#L45-L47). Do you have a log from the action running? It should always output to the log the version it's using. You can use `dry_run` to avoid actually writing to Git.

**Comment by Bargamut** [comment]
I have a log from one of the action runnings with configuration as I wrote above:
```
Download action repository 'zwaldowski/match-label-action@v2'
Download action repository 'zwaldowski/semver-release-action@v1'
##[group]Run zwaldowski/match-label-action@v2
  with:
  allowed: major,minor,patch
##[endgroup]
##[group]Run zwaldowski/semver-release-action@v1
  with:
  bump: minor
  github_token: ***
  prefix: v
  dry_run: false
##[endgroup]
```

And the result of this action is the `0.2.0` tag instead of the `v0.2.0`.

**Comment by zwaldowski** [comment]
Aha! Sorry about that. #5 isn't in v1. I've just tagged v2. You can use `@master` or `@v2`. Please let me know if you still have trouble.

**Comment by Bargamut** [comment]
Thanks a lot!
I'll try it now. )

**Comment by Bargamut** [comment]
Yes, now it works! )
Thanks for answer!

But I have one more problem: if I set a trigger for actions like this:
```
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types:
      - closed
```

The merge is tagged correctly, but there is a failure:
```
##[group]Run zwaldowski/match-label-action@v2
  with:
  allowed: major,minor,patch
##[endgroup]
##[error]Could not find exactly one of the appropriate labels on the PR.
```

How to tag merge commit correctly?
Sorry if the question is not for this repository.
